# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller Spec for DocConvert Standalone Headless MCP Server.
Builds an ultra-lightweight, zero-dependency console executable (~15MB) for Claude Desktop & IDEs.
"""

a_mcp = Analysis(
    ['src/mcp/server.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'src.__version__',
        'src.mcp.server',
        'src.mcp.tools',
        'src.mcp.security',
        'src.services.metadata_index',
        'src.services.fuzzy_matcher',
        'src.services.link_parser',
        'src.services.conversion_service',
        'src.core.base_module',
        'src.core.converters',
        'src.core.error_mapper',
        'src.core.errors',
        'src.core.registry',
        'src.core.validator',
        'src.i18n.translator',
        'src.utils.assets',
        'src.utils.clipboard',
        'src.utils.env',
        'src.utils.file_ops',
        'src.utils.logger',
        'src.utils.settings_store',
        'src.utils.window',
        'src.modules.word_module',
        'src.modules.excel_module',
        'src.modules.pdf_module',
        'src.modules.csv_module',
        'src.modules.html_module',
        'src.modules.pptx_module',
        'src.modules.json_module',
        'src.modules.yaml_module',
        'src.modules.audio_module',
        'src.modules.pdf_scan_module',
        'docx',
        'pptx',
        'openpyxl',
        'markdown_pdf',
        'markdown2',
        'bs4',
        'yaml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude all heavy GUI frameworks & AI speech/vision runtimes
        'flet',
        'flet_desktop',
        'webview',
        'pythonnet',
        'clr',
        'faster_whisper',
        'ctranslate2',
        'onnxruntime',
        'torch',
        'torchaudio',
        'tensorflow',
        'tensorboard',
        'matplotlib',
        'scipy',
        'pandas',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'tkinter',
        'pytest',
        'unittest',
    ],
    noarchive=False,
    optimize=2,
)

pyz_mcp = PYZ(a_mcp.pure)

exe_standalone_mcp = EXE(
    pyz_mcp,
    a_mcp.scripts,
    a_mcp.binaries,
    a_mcp.datas,
    [],
    name='docconvert-mcp-standalone',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,  # Console subsystem enabled for Native Stdio JSON-RPC
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/icons/app_icon.ico'],
)
