; Script generated by Antigravity IDE for Inno Setup 6 / 7
; Document Converter Desktop Application Packaging Script - Multilingual & Self-Contained

#ifndef MyAppVersion
  #define MyAppVersion "1.9.2"
#endif

#define MyAppName "Document Converter"
#define MyAppPublisher "Document Converter Team"
#define MyAppURL "https://github.com/duyphan1410/DocumentConvertTool"
#define MyAppExeName "Document Converter.exe"
#define MyAppId "{{8B598F53-2F47-4C7D-9A92-4A63C1B57801}}"

[Setup]
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Output configuration
OutputDir=..\dist\installer
OutputBaseFilename=Document_Converter_Setup_v{#MyAppVersion}
SetupIconFile=..\assets\icons\app_icon.ico
UninstallDisplayName={#MyAppName} v{#MyAppVersion}
; Compression
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Permissions: default to current user (%LocalAppData%\Programs) without UAC prompt,
; while allowing elevation dialog to install for all users (Program Files).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
; Multilingual setup configuration
ShowLanguageDialog=yes

[Languages]
Name: "vietnamese"; MessagesFile: "Vietnamese.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
english.AdditionalIcons=Additional shortcuts:
vietnamese.AdditionalIcons=Tùy chọn biểu tượng:

english.CreateDesktopIcon=Create a &desktop shortcut
vietnamese.CreateDesktopIcon=Tạo biểu tượng trên màn hình &Desktop

english.AIFeatures=AI Offline Speech Transcriber (Optional):
vietnamese.AIFeatures=Mô hình AI Nhận Diện Giọng Nói Offline (Tùy chọn):

english.DownloadWhisperModel=Pre-download Whisper Base AI Model (~145 MB)%n(Enables instant offline audio/video transcription without waiting. You can skip this and download later in-app)
vietnamese.DownloadWhisperModel=Tải trước mô hình AI Whisper Base (~145 MB)%n(Giúp nhận diện âm thanh/video offline tức thì. Có thể bỏ qua và tải sau trong ứng dụng)

english.WebView2Prompt=Microsoft Edge WebView2 Runtime was not detected on this machine.%n%nDocument Converter requires WebView2 for embedded YouTube transcript companion playback.%n%nWould you like to open Microsoft's official download page now?
vietnamese.WebView2Prompt=Không tìm thấy Microsoft Edge WebView2 Runtime trên máy tính của bạn.%n%nDocument Converter cần WebView2 để phát video và đồng bộ mốc thời gian YouTube.%n%nBạn có muốn mở trang tải về chính thức của Microsoft ngay bây giờ không?

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "downloadmodel"; Description: "{cm:DownloadWhisperModel}"; GroupDescription: "{cm:AIFeatures}"; Flags: unchecked

[Files]
Source: "..\dist\Document Converter\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  DownloadPage: TDownloadWizardPage;

// Helper function to check if Microsoft Edge WebView2 Runtime or Edge is installed
function CheckRegKeyVersion(RootKey: Integer; KeyPath: String): Boolean;
var
  InstalledVersion: String;
begin
  Result := False;
  if RegQueryStringValue(RootKey, KeyPath, 'pv', InstalledVersion) and (InstalledVersion <> '') and (InstalledVersion <> '0.0.0.0') then
    Result := True;
end;

function IsWebView2Installed(): Boolean;
var
  GuidWebView2: String;
  GuidEdgeStable: String;
begin
  Result := False;
  // Official Evergreen WebView2 Runtime GUID
  GuidWebView2 := '{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  // Microsoft Edge Stable GUID
  GuidEdgeStable := '{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}';

  if CheckRegKeyVersion(HKLM64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKCU64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKCU32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM64, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM32, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidEdgeStable) or
     CheckRegKeyVersion(HKLM32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidEdgeStable) then
  begin
    Result := True;
  end;
end;

// Hook to check dependencies before installation proceeds
function InitializeSetup(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  if not IsWebView2Installed() then
  begin
    if MsgBox(CustomMessage('WebView2Prompt'), mbConfirmation, MB_YESNO) = IDYES then
    begin
      ShellExec('open', 'https://go.microsoft.com/fwlink/p/?LinkId=2124703', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
    end;
  end;
end;

// Initialize native Inno Setup download page
procedure InitializeWizard();
begin
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), nil);
end;

// Trigger native in-wizard download if downloadmodel task is selected
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  if CurPageID = wpReady then
  begin
    if WizardIsTaskSelected('downloadmodel') then
    begin
      DownloadPage.Clear;
      DownloadPage.Add('https://huggingface.co/Systran/faster-whisper-base/resolve/main/config.json', 'config.json', '');
      DownloadPage.Add('https://huggingface.co/Systran/faster-whisper-base/resolve/main/model.bin', 'model.bin', '');
      DownloadPage.Add('https://huggingface.co/Systran/faster-whisper-base/resolve/main/tokenizer.json', 'tokenizer.json', '');
      DownloadPage.Add('https://huggingface.co/Systran/faster-whisper-base/resolve/main/vocabulary.txt', 'vocabulary.txt', '');
      DownloadPage.Show;
      try
        try
          DownloadPage.Download;
          Result := True;
        except
          if DownloadPage.AbortedByUser then
            Log('Download aborted by user.')
          else
            MsgBox(CustomMessage('DownloadModelFailed'), mbInformation, MB_OK);
          Result := True;
        end;
      finally
        DownloadPage.Hide;
      end;
    end
    else
      Result := True;
  end
  else
    Result := True;
end;

// Native Pascal procedure to synchronize the chosen setup language directly into settings.json
procedure SyncLanguageToSettings();
var
  SettingsDir: String;
  SettingsFile: String;
  LangCode: String;
  FileLines: TArrayOfString;
  I: Integer;
  Found: Boolean;
  NewContent: String;
begin
  if ActiveLanguage = 'vietnamese' then
    LangCode := 'vi'
  else
    LangCode := 'en';

  SettingsDir := ExpandConstant('{userappdata}\DocConvert');
  SettingsFile := SettingsDir + '\settings.json';

  if not DirExists(SettingsDir) then
    ForceDirectories(SettingsDir);

  if FileExists(SettingsFile) then
  begin
    if LoadStringsFromFile(SettingsFile, FileLines) then
    begin
      Found := False;
      for I := 0 to GetArrayLength(FileLines) - 1 do
      begin
        if Pos('"language"', FileLines[I]) > 0 then
        begin
          FileLines[I] := '  "language": "' + LangCode + '",';
          Found := True;
          Break;
        end;
      end;
      if Found then
      begin
        SaveStringsToFile(SettingsFile, FileLines, False);
      end;
    end;
  end
  else
  begin
    NewContent := '{' + #13#10 + '  "language": "' + LangCode + '"' + #13#10 + '}';
    SaveStringToFile(SettingsFile, NewContent, False);
  end;
end;

// Move downloaded model files from {tmp} to destination models folder
procedure MoveDownloadedModelFiles();
var
  ModelDir: String;
  Files: array[0..3] of String;
  I: Integer;
  SrcFile, DstFile: String;
begin
  ModelDir := ExpandConstant('{userappdata}\DocConvert\models\whisper-base');
  if not DirExists(ModelDir) then
    ForceDirectories(ModelDir);

  Files[0] := 'config.json';
  Files[1] := 'model.bin';
  Files[2] := 'tokenizer.json';
  Files[3] := 'vocabulary.txt';

  for I := 0 to 3 do
  begin
    SrcFile := ExpandConstant('{tmp}\' + Files[I]);
    DstFile := ModelDir + '\' + Files[I];
    if FileExists(SrcFile) then
    begin
      FileCopy(SrcFile, DstFile, False);
      DeleteFile(SrcFile);
    end;
  end;
end;

// Hook on post install
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    SyncLanguageToSettings();

    if WizardIsTaskSelected('downloadmodel') then
    begin
      MoveDownloadedModelFiles();
    end;
  end;
end;
