; Script generated by Antigravity IDE for Inno Setup 6
; Document Converter Desktop Application Packaging Script

#ifndef MyAppVersion
  #define MyAppVersion "1.9.2"
#endif

#define MyAppName "Document Converter"
#define MyAppPublisher "Document Converter Team"
#define MyAppURL "https://github.com/duyphan1410/DocumentConvertTool"
#define MyAppExeName "Document Converter.exe"
#define MyAppId "{{8B598F53-2F47-4C7D-9A92-4A63C1B57801}}"

[Setup]
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Output configuration
OutputDir=..\dist\installer
OutputBaseFilename=Document_Converter_Setup_v{#MyAppVersion}
SetupIconFile=..\assets\icons\app_icon.ico
UninstallDisplayName={#MyAppName} v{#MyAppVersion}
; Compression
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Permissions: default to current user (%LocalAppData%\Programs) without UAC prompt,
; while allowing elevation dialog to install for all users (Program Files).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\dist\Document Converter\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Do not use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Helper function to check if Microsoft Edge WebView2 Runtime or Edge is installed
function CheckRegKeyVersion(RootKey: Integer; KeyPath: String): Boolean;
var
  InstalledVersion: String;
begin
  Result := False;
  if RegQueryStringValue(RootKey, KeyPath, 'pv', InstalledVersion) and (InstalledVersion <> '') and (InstalledVersion <> '0.0.0.0') then
    Result := True;
end;

function IsWebView2Installed(): Boolean;
var
  GuidWebView2: String;
  GuidEdgeStable: String;
begin
  Result := False;
  // Official Evergreen WebView2 Runtime GUID
  GuidWebView2 := '{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  // Microsoft Edge Stable GUID
  GuidEdgeStable := '{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}';

  if CheckRegKeyVersion(HKLM64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKCU64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKCU32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM64, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM32, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\' + GuidWebView2) or
     CheckRegKeyVersion(HKLM64, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidEdgeStable) or
     CheckRegKeyVersion(HKLM32, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + GuidEdgeStable) then
  begin
    Result := True;
  end;
end;

// Hook to check dependencies before installation proceeds
function InitializeSetup(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;

  
  if not IsWebView2Installed() then
  begin
    if MsgBox('Microsoft Edge WebView2 Runtime was not detected on this machine.' + #13#10 + #13#10 +
              'Document Converter requires WebView2 for embedded YouTube transcript companion playback.' + #13#10 + #13#10 +
              'Would you like to open Microsoft''s official download page now?',
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      ShellExec('open', 'https://go.microsoft.com/fwlink/p/?LinkId=2124703', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
    end;
  end;
end;
